version: "3"
services:
  authors:
    image: oharkusha/bff-authors-service:1.0
    container_name: bff-authors-service
    ports:
      - 8081:8081
    networks:
      - mynet
    depends_on:
      zipkin:
        condition: service_started
  books:
    image: oharkusha/bff-books-service:1.0
    container_name: bff-books-service
    ports:
      - 8082:8082
    networks:
      - mynet
    depends_on:
      zipkin:
        condition: service_started
  web-sockets:
    image: oharkusha/bff-web-sockets-service:1.0
    container_name: bff-web-sockets-service
    ports:
      - 8083:8083
    networks:
      - mynet
  redis:
    image: redis:latest
    container_name: bff-redis
    ports:
      - 16379:6379
    networks:
      - mynet

  bff-frontend:
    image: oharkusha/bff-frontend:1.0
    container_name: bff-frontend-service
    ports:
       - 8084:8084
    networks:
      - mynet
    depends_on:
      zipkin:
        condition: service_started

  zipkin:
    image: openzipkin/zipkin
    container_name: bff-zipkin-service
    ports:
      - 9411:9411
#    image: oharkusha/bff-zipkin-service:1.0
#    container_name: bff-zipkin-service
#    ports:
#      - 9411:9411
    networks:
      - mynet
networks:
  mynet: