global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'bff-authors-service:8081', 'bff-books-service:8082', 'cadvisor:8080' ]
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090', 'node-exporter:9100' ]